trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: echo testing pipeline

- powershell: Get-ChildItem -Path '.' -recurse

- task: DownloadSecureFile@1
  name: "DownloadFile"
  inputs:
    secureFile: 'mySecureFile.json'
  displayName: "Download Key"

- powershell: Get-ChildItem -Path $(DownloadFile.secureFilePath) -recurse

- powershell: Get-ChildItem -Path $(Agent.TempDirectory) -recurse

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory) 
    contents: '**.json*'
    targetFolder: fastlane

- powershell: Get-ChildItem -Path fastlane -recurse

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'fastlane'
    artifact: 'fastlaneBuild'
    publishLocation: 'pipeline'
  displayName: 'Publish Artifact'

