trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: echo testing pipeline

- powershell: Get-ChildItem -Path '.' -recurse

- task: DownloadSecureFile@1
  name: "DownloadFile"
  inputs:
    secureFile: 'mySecureFile.json'
  displayName: "Download Key"

- powershell: Get-ChildItem -Path '.' -recurse

